spring.datasource.url=jdbc:postgresql://localhost:5432/sticker_pack
spring.datasource.username=postgres
spring.datasource.password=vma25062005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gigachat.auth-key=${GIGACHAT_AUTH_KEY}

#\u0437\u0430\u0434\u0430\u0435\u043c \u043b\u0438\u043c\u0438\u0442\u044b \u0433\u0435\u043d\u0435\u0440\u0430\u0446\u0438\u0438
generation.rate-limit.max-requests=5
generation.rate-limit.window-minutes=60

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
