spring.datasource.url=jdbc:postgresql://localhost:5432/sticker_pack
spring.datasource.username=postgres
spring.datasource.password=vma25062005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gigachat.auth-key=${GIGACHAT_AUTH_KEY}

spring.mvc.pathmatch.matching-strategy=ant_path_matcher